package com.vyrena.mconbridge.launch

import com.vyrena.mconbridge.domain.ArtemisPayload

object ArtemisArtFile {
    fun encode(payload: ArtemisPayload): String = buildString {
        appendLine("# Artemis app entry")
        appendLine("# Generated by MCON Bridge")
        appendLine()
        appendLine("[host_uuid] ${payload.hostUuid}")
        payload.hostName?.takeIf { it.isNotBlank() }?.let { appendLine("[host_name] $it") }
        payload.appUuid?.takeIf { it.isNotBlank() }?.let { appendLine("[app_uuid] $it") }
        payload.appName?.takeIf { it.isNotBlank() }?.let { appendLine("[app_name] $it") }
        payload.appId?.takeIf { it.isNotBlank() }?.let { appendLine("[app_id] $it") }
    }
}
